### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by thenightex** [thenightex/nyanpansu#3]
update the readme to display important informations.
as always keep it simple.
the page that I'm creating here will serve as some kind of portfolio I guess.

the informations to display would be:
-about myself(I will provide these later or just put them in myself)
-frameworks used seperated into client/server

the current content of this repository shouldn't be taken to serious as I'm just building and testing various things(in terms of texts/images)

**Comment by minibhati93** [comment]
Can you please explain what is to be done? I can work on this

**Comment by thenightex** [comment]
Oh I'm sorry. I didn't think someone would actually end up here.
I've updated the comment above to be a bit more precise for now.

**Comment by thenightex** [comment]
closed for now
about me will be filled in the next days.
technical stuff will be updated once the website and server are "alpha" ready?
