### ISSUE TITLE
create template for contact page

### ISSUE THREAD

**Issue by thenightex** [thenightex/nyanpansu#5]
create handlebars template for contact page
keep it simple
should contain fields for name, email, message?
only talking about the template here and not the logic behind it

**Comment by approdriguez** [comment]
do you mean just the html?

**Comment by thenightex** [comment]
yea as simple as that

**Comment by approdriguez** [comment]
ok, im on it

**Comment by daordonez11** [comment]
Hi, check your pull request, already solved this one :)

**Comment by daordonez11** [comment]
#7
